---

- name: Harden OS (by https://github.com/dev-sec/ansible-collection-hardening)
  hosts: docker_media,k3s_cluster
  roles:
    - devsec.hardening.os_hardening
  vars:
    sysctl_overwrite:
      # Necessary for Docker
      net.ipv4.ip_forward: 1
