[vault_servers]
10.0.20.100

[vault_servers:vars]
ansible_user=ansible
ansible_become=yes

[docker_host]
10.0.20.60

; Move variables to group/vars in the future

[docker_host:vars]
ansible_user=ansible
ansible_become=yes
